### ISSUE TITLE
Miniconda couldn't be installed

### ISSUE THREAD

**Issue by ChiaChing-Yen** [raccoon-ncku/DCCG#1]
![Miniconda installation failed](https://user-images.githubusercontent.com/60199319/190046855-1a4072a5-030f-409b-910f-e42523402a10.png)

Error: Due to incompatibility with several python libraries, 'Destination Folder' cannot contain non-ascii characters (special characters or diacritics). Please choose another location.

**Comment by dadavidtseng** [comment]
My solution is to change the destination folder to (D:) and create a folder with English title.

**Comment by ChiaChing-Yen** [comment]
If anyone encountered this issue, please refer to @dadavidtseng 's solution.
