### ISSUE TITLE
conda 讀取問題 (以下載並執行miniconda但無法讀取)

### ISSUE THREAD

**Issue by jason55094** [raccoon-ncku/DCCG#2]
![messageImage_1663221667485](https://user-images.githubusercontent.com/113578864/190326220-3b10b11b-d822-43ec-b9bf-b47b329b4bbb.jpg)

**Comment by ChiaChing-Yen** [comment]
I think the main issue is that conda couldn't find an environment called `DCCG`. Try executing the following command in Anaconda Powershell Prompt to create one:

```
conda create -n DCCG python -y
```

After that you should be able to `conda activate DCCG` and use it in your VScode.
